/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gft.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Addresses extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4725773141936697864L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Addresses\",\"fields\":[{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"Street\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Addresses> ENCODER =
      new BinaryMessageEncoder<Addresses>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Addresses> DECODER =
      new BinaryMessageDecoder<Addresses>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Addresses> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Addresses> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Addresses>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Addresses to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Addresses from a ByteBuffer. */
  public static Addresses fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence Name;
  @Deprecated public java.lang.CharSequence Street;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Addresses() {}

  /**
   * All-args constructor.
   * @param Name The new value for Name
   * @param Street The new value for Street
   */
  public Addresses(java.lang.CharSequence Name, java.lang.CharSequence Street) {
    this.Name = Name;
    this.Street = Street;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Name;
    case 1: return Street;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Name = (java.lang.CharSequence)value$; break;
    case 1: Street = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Name' field.
   * @return The value of the 'Name' field.
   */
  public java.lang.CharSequence getName() {
    return Name;
  }

  /**
   * Sets the value of the 'Name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.Name = value;
  }

  /**
   * Gets the value of the 'Street' field.
   * @return The value of the 'Street' field.
   */
  public java.lang.CharSequence getStreet() {
    return Street;
  }

  /**
   * Sets the value of the 'Street' field.
   * @param value the value to set.
   */
  public void setStreet(java.lang.CharSequence value) {
    this.Street = value;
  }

  /**
   * Creates a new Addresses RecordBuilder.
   * @return A new Addresses RecordBuilder
   */
  public static Addresses.Builder newBuilder() {
    return new Addresses.Builder();
  }

  /**
   * Creates a new Addresses RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Addresses RecordBuilder
   */
  public static Addresses.Builder newBuilder(Addresses.Builder other) {
    return new Addresses.Builder(other);
  }

  /**
   * Creates a new Addresses RecordBuilder by copying an existing Addresses instance.
   * @param other The existing instance to copy.
   * @return A new Addresses RecordBuilder
   */
  public static Addresses.Builder newBuilder(Addresses other) {
    return new Addresses.Builder(other);
  }

  /**
   * RecordBuilder for Addresses instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Addresses>
    implements org.apache.avro.data.RecordBuilder<Addresses> {

    private java.lang.CharSequence Name;
    private java.lang.CharSequence Street;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Addresses.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Name)) {
        this.Name = data().deepCopy(fields()[0].schema(), other.Name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Street)) {
        this.Street = data().deepCopy(fields()[1].schema(), other.Street);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Addresses instance
     * @param other The existing instance to copy.
     */
    private Builder(Addresses other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Name)) {
        this.Name = data().deepCopy(fields()[0].schema(), other.Name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Street)) {
        this.Street = data().deepCopy(fields()[1].schema(), other.Street);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'Name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return Name;
    }

    /**
      * Sets the value of the 'Name' field.
      * @param value The value of 'Name'.
      * @return This builder.
      */
    public Addresses.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Name' field has been set.
      * @return True if the 'Name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Name' field.
      * @return This builder.
      */
    public Addresses.Builder clearName() {
      Name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Street' field.
      * @return The value.
      */
    public java.lang.CharSequence getStreet() {
      return Street;
    }

    /**
      * Sets the value of the 'Street' field.
      * @param value The value of 'Street'.
      * @return This builder.
      */
    public Addresses.Builder setStreet(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Street = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Street' field has been set.
      * @return True if the 'Street' field has been set, false otherwise.
      */
    public boolean hasStreet() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Street' field.
      * @return This builder.
      */
    public Addresses.Builder clearStreet() {
      Street = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Addresses build() {
      try {
        Addresses record = new Addresses();
        record.Name = fieldSetFlags()[0] ? this.Name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Street = fieldSetFlags()[1] ? this.Street : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Addresses>
    WRITER$ = (org.apache.avro.io.DatumWriter<Addresses>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Addresses>
    READER$ = (org.apache.avro.io.DatumReader<Addresses>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
